[package]
name = "chip8"
version = "0.1.0"
authors = ["Mark <mxrk@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
sdl2 = "0.32"